//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTuiXach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart_detail
    {
        public int id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_cart { get; set; }
    
        public virtual cart cart { get; set; }
        public virtual product product { get; set; }
    }
}
