//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTuiXach.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shoptuixachEntities : DbContext
    {
        public shoptuixachEntities()
            : base("name=shoptuixachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<cart_detail> cart_detail { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<permission> permissions { get; set; }
        public virtual DbSet<product> products { get; set; }
    }
}
